"""
pdf_utils.py
------------
Generates downloadable PDF reports (crop recommendation / disease risk)
using ReportLab. Returns raw bytes so Streamlit's download_button can
serve them without touching disk.
"""

from __future__ import annotations
import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
)

GREEN = colors.HexColor("#2E7D32")
BROWN = colors.HexColor("#6D4C41")
LIGHT_GREEN = colors.HexColor("#E8F5E9")


def _base_doc(buffer: io.BytesIO) -> SimpleDocTemplate:
    return SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=2 * cm, bottomMargin=2 * cm,
        leftMargin=2 * cm, rightMargin=2 * cm,
    )


def _styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="TitleGreen", fontSize=20, textColor=GREEN, spaceAfter=6, fontName="Helvetica-Bold"))
    styles.add(ParagraphStyle(name="SubHeader", fontSize=13, textColor=BROWN, spaceBefore=14, spaceAfter=6, fontName="Helvetica-Bold"))
    styles.add(ParagraphStyle(name="BodySmall", fontSize=10, leading=14))
    return styles


def build_crop_report(inputs: dict, result: dict) -> bytes:
    buffer = io.BytesIO()
    doc = _base_doc(buffer)
    styles = _styles()
    elements = []

    elements.append(Paragraph("🌾 Smart Crop Recommendation Report", styles["TitleGreen"]))
    elements.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles["BodySmall"]))
    elements.append(Spacer(1, 12))

    elements.append(Paragraph("Input Parameters", styles["SubHeader"]))
    input_table_data = [["Parameter", "Value"]] + [[k, str(v)] for k, v in inputs.items()]
    t = Table(input_table_data, colWidths=[7 * cm, 7 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), GREEN),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_GREEN]),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(t)

    elements.append(Paragraph("Recommendation Result", styles["SubHeader"]))
    elements.append(Paragraph(f"<b>Recommended Crop:</b> {result['top_crop'].title()}", styles["BodySmall"]))
    elements.append(Paragraph(f"<b>Confidence:</b> {result['confidence']*100:.1f}%", styles["BodySmall"]))
    elements.append(Spacer(1, 8))

    top5_data = [["Rank", "Crop", "Confidence"]]
    for i, (crop, prob) in enumerate(result["top_k"], start=1):
        top5_data.append([str(i), crop.title(), f"{prob*100:.1f}%"])
    t2 = Table(top5_data, colWidths=[2 * cm, 7 * cm, 5 * cm])
    t2.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BROWN),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_GREEN]),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
    ]))
    elements.append(t2)

    elements.append(Spacer(1, 16))
    elements.append(Paragraph(
        "This report is generated by an ML-based decision-support tool for educational/portfolio "
        "purposes. Validate recommendations with a local agricultural expert before field application.",
        styles["BodySmall"],
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()


def build_disease_report(inputs: dict, result: dict, guidance: dict) -> bytes:
    buffer = io.BytesIO()
    doc = _base_doc(buffer)
    styles = _styles()
    elements = []

    elements.append(Paragraph("🦠 Disease Risk Prediction Report", styles["TitleGreen"]))
    elements.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles["BodySmall"]))
    elements.append(Spacer(1, 12))

    elements.append(Paragraph("Input Parameters", styles["SubHeader"]))
    input_table_data = [["Parameter", "Value"]] + [[k, str(v)] for k, v in inputs.items()]
    t = Table(input_table_data, colWidths=[7 * cm, 7 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), GREEN),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_GREEN]),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
    ]))
    elements.append(t)

    elements.append(Paragraph("Prediction Result", styles["SubHeader"]))
    elements.append(Paragraph(f"<b>Risk Level:</b> {result['risk_level']}", styles["BodySmall"]))
    elements.append(Paragraph(f"<b>Confidence:</b> {result['confidence']*100:.1f}%", styles["BodySmall"]))
    elements.append(Spacer(1, 8))

    elements.append(Paragraph("Prevention Tips", styles["SubHeader"]))
    for tip in guidance["prevention"]:
        elements.append(Paragraph(f"• {tip}", styles["BodySmall"]))

    elements.append(Paragraph("Organic Treatment Options", styles["SubHeader"]))
    for tip in guidance["organic_treatment"]:
        elements.append(Paragraph(f"• {tip}", styles["BodySmall"]))

    elements.append(Paragraph("Chemical Treatment Options", styles["SubHeader"]))
    for tip in guidance["chemical_treatment"]:
        elements.append(Paragraph(f"• {tip}", styles["BodySmall"]))

    elements.append(Spacer(1, 16))
    elements.append(Paragraph(
        "General agronomic guidance only — not a substitute for lab diagnosis or professional "
        "agricultural extension advice.",
        styles["BodySmall"],
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()
